apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mickey
  name: mickey
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mickey
  template:
    metadata:
      labels:
        app: mickey
        version: v1
      name: mickey
    spec:
      containers:
      - name: mickey
        image: austin1week.azurecr.io/mickey:1.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: mickey
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: mickey